### ISSUE TITLE
[LGSM] autoupdate working?

### ISSUE THREAD

**Issue by medic917** [dgibbs64/linuxgameservers#181]
Hi Daniel,
I saw that you enabled -autoupdate (unless I'm incorrect).

I keep getting steam directory is missing error, have anyone used it successfully with Daniel's script?

By any chance can you make a query script like your monitor query script, so when steam gives the server needs an update message it will auto trigger an update?

willing to donate if you can do this, it has become a pain to see my servers empty since the game devs did an update mid-day.

**Comment by dgibbs64** [comment]
New feature released for auto updates. The script can now check for updates and only restart the server if required.
