### ISSUE TITLE
[fn_details] Re-do ports with printf or simular

### ISSUE THREAD

**Issue by dgibbs64** [dgibbs64/linuxgameservers#227]
I woudl like the ports table redone with a tool like printf rather than echo as printf will line up the data rather than manualy aligning using tabs with echo. This will make the data printed look neater

edit: I am working on a major overhall of details to display more useful info and make is look better.

**Comment by dgibbs64** [comment]
Here is a mockup of what it may look like. Let me know what you think

	Counter Strike: Source Server Details
	==========================================
	Server name:    css-server
	Server IP:      192.168.1.1:27015
	RCON password:  rconpassword
	Status: 		ONLINE

	Service name:  css-server
	User:          cssserver
	Location:      /home/cssserver
	Config file:   /home/cssserver/serverfiles/cstrike/cfg/css-server.cfg

	Start Parameters
	============================
	./srcds_run -game cstrike -strictportbind -ip 92.222.219.75 -port 27015 +clientport 27005 +tv_port 27020 +map de_dust2 +servercfgfile css-server.cfg -maxplayers 16

	Backups
	============================
	No. of backups:  1
	Latest backup:
	    date:        Tue Jan 13 22:44:46 CET 2015
	    file:        /home/cssserver/backups/css-server-2015-01-13-224440.tar.gz
	    size:        10M

	Server Ports
	============================
	You can change ports by editing the
	start parameters in ./cssserver.

	 DESCRIPTION  	PORT 	DIRECTION	STATUS
	 > Game/RCON    27015	in  	 	LISTEN
	 > SourceTV     27020	in 		
	 < Client       27005	out  

	Distro Details
	=========================================
	Distro:    Debian 7.7
	Arch:      x86_64
	Kernel:    2.6.32-042stab094.7
	Hostname:  vps86887.ovh.net
	tmux:      tmux 1.6
	GLIBC:     2.13

	Performance
	============================
	Uptime: 1d, 14h, 54m
	Avg Load: 0.00, 0.00, 0.00

	Mem:		total       used       free
	Physical:	1.0G       276M       747M
	Swap:		128M         0B       128M


	Disk Usage
	============================
	Total: 			1TB
	Available:  	7.2G
	Serverfiles:     2.2G
	Backups:         4.0K

	Status: ONLINE

**Comment by dgibbs64** [comment]
New feature now with new release https://github.com/dgibbs64/linuxgameservers/commit/c912c4d2bd2939eeb701368aa811884de933689a

**Comment by Xylemon** [comment]
That looks much better.
