### ISSUE TITLE
[ss3server] GLIBC fix required

### ISSUE THREAD

**Issue by lblanchardiii** [dgibbs64/linuxgameservers#245]
This is the error I get in the log:

ldd: ./Sam3: No such file or directory
ldd: ./Sam3: No such file or directory
cat: /etc/debian_version: No such file or directory
ERR:  Lua error: [string "dofile("Content/SeriousSam3/Config/ss3-serv..."]:1: Cannot open file Content/SeriousSam3/Config/ss3-server.ini
INF:  Lua stack traceback:
INF:      [C]: in function dofile
INF:      [string "dofile("Content/SeriousSam3/Config/ss3-serv..."]:1: in main chunk
LOG:  Loaded "/home/ss3/serverfiles/Bin/GameEnv_Steam.so".
INF:  GameEnv API: Steam
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
dlopen failed trying to load:
steamclient.sowith error:
/usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by /home/ss3/serverfiles/Bin/steamclient.so)
[S_API FAIL] SteamAPI_Init() failed; unable to locate a running instance of Steam, or a local steamclient.dll.

Running CentOS 6.6 as the Operating System.

**Comment by dgibbs64** [comment]
Closing reference this issue instead https://github.com/dgibbs64/linuxgameservers/issues/247
