### ISSUE TITLE
Error! App '90' state is 0x406 after update job.

### ISSUE THREAD

**Issue by KeanePW** [dgibbs64/linuxgameservers#252]
I couldn't install CS server using server manager on Ubuntu 14.04 due to error:

Error! App '90' state is 0x406 after update job.

I've reported this error to half life:

https://github.com/ValveSoftware/halflife/issues/1583

Is there anything that can be done in the server manager script to resolve this?

**Comment by Scarsz** [comment]
This might be one of those "keep hitting it until it works" problems. Try restarting the installation over and over again until it fixes itself.

**Comment by KeanePW** [comment]
Thank you for your response. I spent most of the day retrying the installation. However, it stops at exactly the same place every single time. This is a new dedicated server with a fresh install of Ubuntu. The server is being installed as a user csserver as per the CS manager instructions.

**Comment by dgibbs64** [comment]
@KeanePW its an issue with SteamCMD im afraid and out of our control. I have however with the next update I have added a loop in to the installer that will retry 10 times before giving up should it fail. There have been quite a few issues with SteamCMD and gold source games like cs 1.6 in the past. Was hoping they have fixed them all now

**Comment by KeanePW** [comment]
No worries I understand it's out of your control. That loop in the next update is truly awesome Daniel. I'm a big fan of your work. Thank you very much.

**Comment by dgibbs64** [comment]
Cheers buddy. Always nice to hear my work is useful. Its one of the main reason I enjoy working on this project. :D

**Comment by dgibbs64** [comment]
This feature is now implemented. It wont fix the issue but trying several times might get it to kick in to life.

https://github.com/dgibbs64/linuxgameservers/commit/57789b0c109a723be9250b1f60d9374674d57cdb

**Comment by RAlexander3** [comment]
It is still asking if you would like to retry. The you have to enter N, Y, Y then it will start again. Is this intended to work this way?

**Comment by dgibbs64** [comment]
It should automatically try 10 times before asking to retry. If you haven't already delete the functions dir and try again. If still not trying 10 times its a bug.

**Comment by Flake16** [comment]
Like RAlexander3 wrote, the Script do not recognize Error 0x406 and repeat automatically.
After several manual restarts i got the message:
"Failure! SteamCMD did not complete the download, too many retrys"

**Comment by dgibbs64** [comment]
Thanks for the update. I recommend logging the issue with Valve on there github to fix the issue. They seemed to fix it for a while. In the mean time I will get the code working as inteanded.

**Comment by dgibbs64** [comment]
Found the issue i originaly raised https://github.com/ValveSoftware/halflife/issues/1541

**Comment by dgibbs64** [comment]
I am adding in all the error codes that are being provided. If it sees any of these errors it will retry the download.

**Comment by lnxprof** [comment]
I had chased this issue down the rabbit hole a while back and found that it consistently happened ONLY on my Virtualized hosts that had write-through cache enabled.  If that applies to your situation, try turning it off for a test.  It'd be good to have someone either validate my observation or chime in that it's happening in situations other than VMs with cached disk I/O.

**Comment by tenpin784** [comment]
Just want to post and say that I have been trying to install a TFC server a good portion of the day, and has failed every time. It is a vps machine. 

I have followed the instructions toa T, and still fails. Then I would wipe the homedir and start again, and fail again. Even retrying the install doesn't seem to help.

**Comment by tenpin784** [comment]
I finally got TFC to install, had to do a bit of manual labor for it to go

In tfcserver home folder:

[code]
mkdir steamcmd
cd steamcmd
wget -N --no-check-certificate /dev/null http://media.steampowered.com/client/steamcmd_linux.tar.gz 2>&1 | grep -F HTTP | cut -c45-| uniq
tar --verbose -zxf steamcmd_linux.tar.gz
rm -v steamcmd_linux.tar.gz
chmod +x steamcmd.sh
cd ..
mkdir serverfiles
steamcmd/steamcmd.sh

--- inside the CLI for steamcmd  ---
login anonymous
app_set_config 90 mod tfc
app_update 90 (failed with 0x106)
app_update 90 (said installed successfully)
app_update 90 validate (this is when it downloaded the big chunk of data)
app_update 90 validate (just to make sure)
quit

------ back to linux CLI  ---

./tfcserver install (finally succeeded).

[/code]

The problem the tfcserver install script was having was, after it installed, under "serverfiles", I never had a "tfc" folder. I would always have "valve" and "cstrike" for folders, but never "tfc". When I did the server installation manually, I finally had a TFC server.

Hope this helps someone, or maybe helps with the script building.

**Comment by dgibbs64** [comment]
Some decent suggestions here. I will have to test these out. Of it works I could create an install function just for goldsrc games. At the very least it might improve the chances of there not being an issue.

**Comment by tenpin784** [comment]
I think the issue might be with the app ID in the script. I have tried 
putting it different ways, but couldn't get it to work.

I know I am working with a much older game, but hey, if you're going to 
provide it (it helps me out now, especially since it's running), should 
try and make it right. And I would not mind helping any way I can.

Thanks!
--John

**Comment by dgibbs64** [comment]
The other thing you can do is post on the Valve github issue for this as it's Vavles problem. The more people that post about it the better. All I can do is implement a workaround for there problem.

**Comment by dgibbs64** [comment]
I have implimented a work around for this issue to try and help. However there is nothing else I can do. Closing this issue now

**Comment by mo0nsniper** [comment]
If someone needs the hlds cstrike server I have a zip archive saved from today.
The validate process stops and gives a strange error at 98. % but the game server is running.

Link here: http://miez.ro/cstrike/hlds.zip
Slow mirror here: https://content.wuala.com/contents/mo0n_sniper/Proiecte/cstrike/server/hlds/linux/hlds.zip/?dl=1&key=server

**Comment by hitmany** [comment]
@KeanePW So maybe you will make option which checking this error and if update reciveing error its will try update again. I think it help)
