### ISSUE TITLE
[LGSM] Re-download SteamCMD if missing

### ISSUE THREAD

**Issue by dgibbs64** [dgibbs64/linuxgameservers#253]
If the steamCMD dir is missing re download

**Comment by Scarsz** [comment]
Does this not already happen https://github.com/dgibbs64/linuxgameservers/blob/master/functions/fn_steamdl#L11#L14

**Comment by dgibbs64** [comment]
This feature is not implemented.

https://github.com/dgibbs64/linuxgameservers/commit/6f560a9acb7a3067b64c5d761a571134b4c00812
