### ISSUE TITLE
[ut2k4server] Commands not found

### ISSUE THREAD

**Issue by RAlexander3** [dgibbs64/linuxgameservers#257]
[ut2k4server@server ~]$ ./ut2k4server start
./ut2k4server: line 186: fn_startserver: command not found

I noticed you have been changing a lot of code today. Maybe this has something to do with it.

**Comment by dgibbs64** [comment]
Yup its probably a bug I didn't spot. I will fix asap. Thanks for spotting this.

**Comment by dgibbs64** [comment]
Try deleting the functions dir as you may have outdated functions.

**Comment by RAlexander3** [comment]
That did not work.
Tried removing the functions directory and running the install again. Same error.

**Comment by Scarsz** [comment]
When starting the script it gives this too.
`./ut2k4server: line 161: fn_rootcheck: command not found`

**Comment by dgibbs64** [comment]
Fixed :)
https://github.com/dgibbs64/linuxgameservers/commit/64a32515a08b39b507aeb6595ff71437da966612

**Comment by RAlexander3** [comment]
Not sure its fixed. Now it does not download the server files.


=================================
Unreal Tournament 2004
Linux Game Server Manager
by Daniel Gibbs
http://danielgibbs.co.uk
=================================
./ut2k4server: line 66: fn_ut2k4filesdl: command not found
Installing Unreal Tournament 2004 Server
=================================
Extracting dedicatedserver3339-bonuspack.zip
unzip:  cannot find or open dedicatedserver3339-bonuspack.zip, dedicatedserver3339-bonuspack.zip.zip or dedicatedserver3339-bonuspack.zip.ZIP.
Extracting ut2004-lnxpatch3369-2.tar.bz2
tar (child): ut2004-lnxpatch3369-2.tar.bz2: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

**Comment by dgibbs64** [comment]
Ouphs i forgot to add the functions to fn_functions. I have now resolved that issue as well. remove functions dir again to reload them.

**Comment by RAlexander3** [comment]
that did it. 

Thanks for the great work!!
