### ISSUE TITLE
[fofserver] requirements might have changed with 1/2/15 release

### ISSUE THREAD

**Issue by lnxprof** [dgibbs64/linuxgameservers#258]
The 1/2/15 server update introduced a new shared library requirement that will likely require a tweak to the lgsm deployment.  The missing package that fixed it for my servers running LGSM was libcurl4-openss-dev:i386.

See thread here: http://steamcommunity.com/app/265630/discussions/6/620700960896454242/

The developer (R_Yell) alluded to a new update to fix the issue, but no update has been pushed out as of yet.

**Comment by dgibbs64** [comment]
I will give them some time to fix this. They broke another update they did recently and fixed in a few days. Not worth me changing anything if they are going to fix this themselves.

**Comment by dgibbs64** [comment]
Looks fixed by the devs
