### ISSUE TITLE
[arma3server] Arma 3 Server RPT Log Missing

### ISSUE THREAD

**Issue by KeanePW** [dgibbs64/linuxgameservers#259]
Hi,

Just a quick bug report here.

The Arma 3 Server RPT Log is missing.

New machine, fresh install - RPT log is always missing.

This is a useful log to read for debugging any issues with the server.

Regards

**Comment by dgibbs64** [comment]
Just found this http://feedback.arma3.com/view.php?id=19945 which should mean that the logs you are looking for are located in the console log "log/console" as all the servers output from the terminal is output to console logs. Let me know if this is correct. Thanks

**Comment by KeanePW** [comment]
Hi,

Thank you so much for your help. You're epic man. I found the log folder and proceeded to the console folder, and it does indeed hold files but the log files are empty.

arma3server@RS158:~/log/console$ ll
total 8
drwxrwxr-x 2 arma3server arma3server 4096 Jan  7 07:24 ./
drwxrwxr-x 4 arma3server arma3server 4096 Jan  4 13:58 ../
-rw-rw-r-- 1 arma3server arma3server    0 Jan  4 13:58 arma3-server-console-04-01-2015-13-59-01.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan  4 14:15 arma3-server-console-04-01-2015-14-15-23.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan  4 14:16 arma3-server-console-04-01-2015-14-16-07.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan  4 14:19 arma3-server-console-04-01-2015-14-19-18.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan  4 14:21 arma3-server-console-04-01-2015-14-21-28.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan  4 14:25 arma3-server-console-04-01-2015-14-25-12.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan  4 14:40 arma3-server-console-04-01-2015-14-40-08.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan  4 14:44 arma3-server-console-04-01-2015-14-44-37.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan  4 14:46 arma3-server-console-04-01-2015-14-46-18.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan  4 15:09 arma3-server-console-04-01-2015-15-09-44.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan  4 15:18 arma3-server-console-04-01-2015-15-18-38.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan  4 15:28 arma3-server-console-04-01-2015-15-28-04.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan  4 22:06 arma3-server-console-04-01-2015-22-06-22.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan  4 22:09 arma3-server-console-04-01-2015-22-09-01.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan  5 05:00 arma3-server-console-05-01-2015-05-00-01.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan  5 05:00 arma3-server-console-05-01-2015-12-57-01.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan  5 12:59 arma3-server-console-05-01-2015-12-59-01.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan  5 22:07 arma3-server-console-05-01-2015-22-07-56.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan  5 22:10 arma3-server-console-05-01-2015-22-10-41.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan  5 22:20 arma3-server-console-05-01-2015-22-20-22.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan  5 22:31 arma3-server-console-05-01-2015-22-31-51.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan  5 22:40 arma3-server-console-05-01-2015-22-40-39.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan  5 22:42 arma3-server-console-05-01-2015-22-42-11.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan  5 22:45 arma3-server-console-05-01-2015-22-45-38.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan  6 05:00 arma3-server-console-06-01-2015-05-00-01.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan  6 05:00 arma3-server-console-06-01-2015-20-50-13.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan  6 20:57 arma3-server-console-06-01-2015-20-57-00.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan  6 20:59 arma3-server-console-06-01-2015-20-59-33.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan  6 21:46 arma3-server-console-06-01-2015-21-46-16.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan  7 05:00 arma3-server-console-07-01-2015-05-00-01.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan  7 05:00 arma3-server-console-07-01-2015-07-24-01.log
arma3server@RS158:~/log/console$ pwd
/home/arma3server/log/console
arma3server@RS158:~/log/console$

**Comment by dgibbs64** [comment]
No problem. Check your tmux version please  

    tmux -V

**Comment by KeanePW** [comment]
arma3server@RS158:~$ tmux -V
tmux 1.8

Sometimes I do see feedback about tmux (I redacted any IP/server name):

arma3server@RS158:~$ /home/arma3server/arma3server restart
[ .... ] redacted|LinuxAltisLifeRPGModServer/home/arma3server/functions/fn_stopserver: line 15: fn_tmuxcheck: command not found
[  OK  ] redacted|LinuxAltisLifeRPGModServer
[ .... ] redacted|LinuxAltisLifeRPGModServer/home/arma3server/functions/fn_startserver: line 21: fn_tmuxcheck: command not found
[  OK  ] redacted|LinuxAltisLifeRPGModServer
arma3server@RS158:~$ /home/arma3server/arma3server monitor
[  OK  ] Checking session: OK
[  OK  ] Querying port: redacted:2303 : OK

**Comment by Scarsz** [comment]
Don't worry about fn_tmuxcheck not found errors, just a small, non-critical error in the scripts coding.

**Comment by KeanePW** [comment]
Thanks here are a few similar errors noticed, just for your information.

## Backup

Backup created: backups/arma3-server-2015-01-07-214729.tar.gz

/home/arma3server/functions/fn_backupserver: line 59: fn_printcompletenl: command not found

arma3server@RS158:~$

## Restart

/home/arma3server/functions/fn_stopserver: line 15: fn_tmuxcheck: command not found

/home/arma3server/functions/fn_startserver: line 21: fn_tmuxcheck: command not found

## Console

Press "CTRL+b d" to exit console.
/home/arma3server/functions/fn_console: line 17: fn_printwarningnl: command not found

**Comment by Scarsz** [comment]
Have you tried updating the script? I looked into the related coding and as far as I could see it should be working.

**Comment by dgibbs64** [comment]
Yeah it doesn't make sense to me as I am not having this issue. It may just be that the arma3server file needs updating.

**Comment by KeanePW** [comment]
When I used this on a 64-Bit system there were no tmux errors for me either. They only occurred on my 32-Bit installation. Ubuntu 14.04 always. I don't use VMware/VDS installations for game servers, only real machines - dedicated servers. The script files are the latest, I deleted the functions folder as requested, and the new functions were downloaded. The error has disappeared from the monitor function, so whatever you changed there has worked, however the other functions stated above still have the warning error messages. As you said these warnings do not stop the function from taking place, it's just nicer to not see errors. I would fix them myself, but everything works so there is no need. I consider it only a low priority cosmetic change, but I report it to you guys as you may not want errors showing.

**Comment by dgibbs64** [comment]
I will have to load my VM with Ubuntu 14.04 x 32 and try to replicate the issue. Your Tmux version is good. If lower than tmux 1.6 console log does not work because the required feature does not exist. 

A few people have had the command not found issue with fn_printwarningnl however the function does exist in fn_messages file and I don't get the issue when testing. Maybe Ubuntu 14.04 x32 will help.

**Comment by KeanePW** [comment]
What exactly needs to be updated? Previously in this thread I read it's just the functions folder, and perhaps the arma3server file? That file I've not updated, as it's got my configuration in and I don't want to re-install the server just to fix one file. If I need to update the one main file, how do I do that without removing anything else? I want my server to stay online. Thank you all for your input.

**Comment by dgibbs64** [comment]
Easiest thing to do is compare the current arma3server file with the new one. Copy all your changes across and overwrite the current one. Recent updates only change the functions in the file and not configuration. Eventually I will move everything out of that file so it never needs to be updated. Remember to backup your server and only do it when the server is empty so you can test.

**Comment by KeanePW** [comment]
Got all my logs (they're in netlog files). Got all the updates (that solved any errors). Can't wait for the update where it's easy to update the main file. It was pretty easy anyway, didn't even need to stop my server. Just renamed my old file, downloaded new, made edits to the file and ran the commands I need. Everything is working as expected. This is an awesome script.

**Comment by dgibbs64** [comment]
Good stuff. I like to think its pretty awesome :+1: I will close this issue now its fixed :)

**Comment by Scarsz** [comment]
Glad everything is working as it should. :)

**Comment by webzi** [comment]
Hi there.

Just opening this again.

I can´t find any RPT logs. I checked the log folder, and the files in there - No one of them got any that looks like it comes from the server.

$ cat /log/script/arma3-server-script-14-01-2016-21-00-01.log
Jan 14 18:43:48 arma3-server: Starting: Started                                         Server #1
Jan 14 21:00:01 arma3-server: Restarting:                                       Server #1
Jan 14 21:00:01 arma3-server: Stopping:                                         Server #1
Jan 14 21:00:02 arma3-server: Stopping: Stopped                                        Server #1
Jan 14 21:00:03 arma3-server: Starting:                                         Server #1
Jan 14 21:00:04 arma3-server: Starting: Rotating log files


cat /log/console/arma3-server-console.log
Console logging disabled: Bug in tmux 1.8 breaks logging
http://gameservermanagers.com/tmux-upgrade
Currently installed: tmux 1.8
