### ISSUE TITLE
[BSserver] Can't update the server after patch

### ISSUE THREAD

**Issue by raffle2** [dgibbs64/linuxgameservers#264]
Hi,
I have been using your blade symphony guide for multiple servers. Everything worked flawlessly for months but in the last patch the server did not work after updating. 
I checked the servers ftp and a lot of base files were gone so i decided to do a fresh installation and i got this:
http://a.pomf.se/dnzxno.png
Seems like something is blocking the update. I tried with my steam account info and a friends. Same result.
Do you have any idea what is causing this?

Thanks for reading.

**Comment by Scarsz** [comment]
Check the serverfiles directory, are all the files that should be there present?

**Comment by raffle2** [comment]
Thanks for the quick reply.
Before i tried to do this fresh installation, i did see a lot of stuff was gone. That's the main reason i decided to reinstall the server.

**Comment by raffle2** [comment]
Also, i am not the only person who has this issue, other server hosters that used the guide have the same issue.

**Comment by Scarsz** [comment]
What OS are you running?

**Comment by raffle2** [comment]
I am running x32 Ubuntu 12.04 i386

**Comment by Scarsz** [comment]
Unfortunately I don't have access to the blade symphony server files so I can't really debug this. Can you screenshot the contents of the serverfiles folder?

**Comment by dgibbs64** [comment]
@Scarsz Looks like the script is looping for no reason. Its only meant to loop if there is an error code

**Comment by dgibbs64** [comment]
Just updated the fn_steaminstall function. Please delete the functions dir to re-install
https://github.com/dgibbs64/linuxgameservers/commit/d0194138109c840dd9f37a8a112321dfbbf02aa4
Let me know if this helps or not. Thanks

**Comment by raffle2** [comment]
It's working perfectly now! Thank you so much for the fast fix.

**Comment by fug4life** [comment]
@ Daniel and Scarsz, Thanks for your help!

If either of you two are interested in giving Blade Symphony a spin, let me know and I'll send you both a copy.

**Comment by Scarsz** [comment]
@fug4life I'm pretty sure Daniel already has Blade Symphony but if you'd be generous to send one my way I'd definitely give it a try. http://steamcommunity.com/id/ScarszRawr

**Comment by fug4life** [comment]
Sent you a friends invite.

**Comment by dgibbs64** [comment]
Yeah I have a copy. Thanks for the offer. :-)

**Comment by fug4life** [comment]
No worries, sent you some beer money instead, err I mean server running cost donation, enjoy!

**Comment by dgibbs64** [comment]
haha cheers @fug4life donations are always gratefully received. I will enjoy a cold one on you ;-D
