### ISSUE TITLE
Unable to install csgoserver correctly

### ISSUE THREAD

**Issue by alterlai** [dgibbs64/linuxgameservers#265]
Hello,

This is my first time trying to install a csgoserver this way. Previously i've used other software, but i've decided to give this a try since it looks so simple.

So to start things off:
I'm just following the instructions here:
http://danielgibbs.co.uk/lgsm/csgoserver/#comment-1227914682

But then after i do ./csgoserver it'll hang at this step:
http://i.gyazo.com/75fe1e8067e5fd0d2787279ab7b9c908.png

Can some friendly fella help me out here? I don't know if i'm just doing something wrong or if it's something to do with steamcmd like in this post
https://github.com/dgibbs64/linuxgameservers/issues/264

Sidenote: Running Ubuntu 14.04.1 LTS (GNU/Linux 3.13.0-32-generic x86_64)

**Comment by Scarsz** [comment]
Replace line 22 of functions/fn_steaminstall with `cat .fn_steaminstall.tmp > steaminstall.txt` then rerun the install command. Paste us the contents of steaminstall.txt.

**Comment by alterlai** [comment]
I did what you suggested but the outcome is still the same. And no steaminstall.txt file was created.

**Comment by Scarsz** [comment]
Are you positive? `find . -name steaminstall.txt`

**Comment by alterlai** [comment]
http://i.gyazo.com/eb287839060267876f0e68a949e494ce.png

**Comment by dgibbs64** [comment]
There is some sort of issue with SteamCMD here as you can see from your error message.    

    ./steamcmd.sh: line 25: 2531 Segmentation fault

Make sure the the dependencies are installed correctly.

    apt-get install tmux gdb mailutils postfix lib32gcc1

I don't know what the issue is myself but a quick google of the seg error might shed some light

**Comment by alterlai** [comment]
Alright i'll try and find some answers on google.
Also, all the above dependencies are installed.

**Comment by dgibbs64** [comment]
I reckon its something with the server being 64-bit. Please let me know what you find.

**Comment by alterlai** [comment]
Do you think it's worth installing 32 bit and see if that works?

**Comment by alterlai** [comment]
Not much luck finding an answer on Google.

**Comment by dgibbs64** [comment]
Someone in this post suggests disableing SELinux (

**Comment by dgibbs64** [comment]
I think someone else was having an issue with Ubuntu 14.04. Maybe there is an issue there.

**Comment by alterlai** [comment]
Downloading Centos 32 bit atm, see if that'll work

**Comment by alterlai** [comment]
Fixed the issue with this post:
https://github.com/dgibbs64/linuxgameservers/issues/266
