### ISSUE TITLE
"SteamCMD did not complete the download, too many retries!"

### ISSUE THREAD

**Issue by thryckz** [dgibbs64/linuxgameservers#266]
I'm getting that error when I try to initially install the server. I am running a ubuntu server with all of the dependencies installed. When I setup a server without LGS, it works fine. However I want to use the script because of the ease of access of everything and since it's the closet thing to a control panel for games I can afford.
So yeah, can someone help me out with this?
Ubuntu 14.10

**Comment by dgibbs64** [comment]
Can you send a screenshot of the installer please. Is there any error message being displayed?

**Comment by ZoD123** [comment]
I have the same problem (all iptable ports are open)

Update state (0x81) committing, progress: 58,71 (4781759412 / 8144583860)
 Update state (0x81) committing, progress: 58,73 (4783429605 / 8144583860)
 Update state (0x81) committing, progress: 58,75 (4784552197 / 8144583860)
 Update state (0x81) committing, progress: 58,78 (4787134465 / 8144583860)
 Update state (0x81) committing, progress: 62,64 (5101391727 / 8144583860)
 Update state (0x81) committing, progress: 73,16 (5958721081 / 8144583860)
 Update state (0x81) committing, progress: 73,19 (5961028605 / 8144583860)
 Update state (0x81) committing, progress: 73,29 (5968818146 / 8144583860)
 Update state (0x81) committing, progress: 92,96 (7570975863 / 8144583860)
 Update state (0x81) committing, progress: 93,00 (7574070982 / 8144583860)
Success! App '222860' fully installed.
Warning! SteamCMD did not complete the download, retrying: Attempt 2
Redirecting stderr to '/home/l4d2server/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.

Connecting anonymously to Steam Public...Logged in OK
Waiting for license info...OK
Success! App '222860' already up to date.
Warning! SteamCMD did not complete the download, retrying: Attempt 3
Redirecting stderr to '/home/l4d2server/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.

Connecting anonymously to Steam Public...Logged in OK
Waiting for license info...OK
Success! App '222860' already up to date.
Warning! SteamCMD did not complete the download, retrying: Attempt 4
Redirecting stderr to '/home/l4d2server/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.

Connecting anonymously to Steam Public...Logged in OK
Waiting for license info...OK
Success! App '222860' already up to date.
Warning! SteamCMD did not complete the download, retrying: Attempt 5
Redirecting stderr to '/home/l4d2server/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.

Connecting anonymously to Steam Public...Logged in OK
Waiting for license info...OK
Success! App '222860' already up to date.
Warning! SteamCMD did not complete the download, retrying: Attempt 6
Redirecting stderr to '/home/l4d2server/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.

Connecting anonymously to Steam Public...Logged in OK
Waiting for license info...OK
Success! App '222860' already up to date.
Warning! SteamCMD did not complete the download, retrying: Attempt 7
Redirecting stderr to '/home/l4d2server/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.

Connecting anonymously to Steam Public...Logged in OK
Waiting for license info...OK
Success! App '222860' already up to date.
Warning! SteamCMD did not complete the download, retrying: Attempt 8
Redirecting stderr to '/home/l4d2server/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.

Connecting anonymously to Steam Public...Logged in OK
Waiting for license info...OK
Success! App '222860' already up to date.
Warning! SteamCMD did not complete the download, retrying: Attempt 9
Redirecting stderr to '/home/l4d2server/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.

Connecting anonymously to Steam Public...Logged in OK
Waiting for license info...OK
Success! App '222860' already up to date.
Warning! SteamCMD did not complete the download, retrying: Attempt 10
Redirecting stderr to '/home/l4d2server/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.

Connecting anonymously to Steam Public...Logged in OK
Waiting for license info...OK
Success! App '222860' already up to date.
Failure! SteamCMD did not complete the download, too many retrys

**Comment by dgibbs64** [comment]
Looks like multiple people have the issue. I will investigate this.

**Comment by dgibbs64** [comment]
I have replicated the issue. An update will be released

**Comment by ZoD123** [comment]
that sounds gread. Thanks a lot

**Comment by dgibbs64** [comment]
Hopefully resolved the issue. Please test and let me know. I was working on an update anyway. Just got it out quicker. Im no longer getting the issue with the update.
https://github.com/dgibbs64/linuxgameservers/commit/d0194138109c840dd9f37a8a112321dfbbf02aa4

Delete the functions dir to download the update.

**Comment by ZoD123** [comment]
just deleting the functions dir and not more? Installation is triggered, I let you know if all worked fine

**Comment by alterlai** [comment]
Same problem here, i'll try the update. Thank gibbs!

**Comment by alterlai** [comment]
Works like a charm now! Respect for dgibbs64!

**Comment by ZoD123** [comment]
ok it's working. Thanks

**Comment by DooMFeaR** [comment]
Can someone help me with this error? Cannot connect to steam public. Tried everyday for the last week. :(
![untitled](https://cloud.githubusercontent.com/assets/11584706/6764869/baa33e0c-cfce-11e4-9377-e445b7cb45c1.png)
