### ISSUE TITLE
When you send a test email, an error appears saying the console log file does not exist

### ISSUE THREAD

**Issue by KeanePW** [dgibbs64/linuxgameservers#269]
When you send a test email using:

 /home/arma3server/arma3server email-test

There is an error saying the console log file doesn't exist.

## Error with email redacted:

arma3server@RS158:~$ /home/arma3server/arma3server email-test
[ .... ] Email arma3-server: Sending notification to email@here.comtail: cannot open '/home/arma3server/log/console/arma3-server-console.log' for reading: No such file or directory

## Logs which do exist:

arma3server@RS158:~$ ll /home/arma3server/log/console/
total 8
drwxrwxr-x 2 arma3server arma3server 4096 Jan 13 19:55 ./
drwxrwxr-x 4 arma3server arma3server 4096 Jan  4 13:58 ../
-rw-rw-r-- 1 arma3server arma3server    0 Jan  5 22:07 arma3-server-console-05-01-2015-22-07-56.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan  5 22:10 arma3-server-console-05-01-2015-22-10-41.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan  5 22:20 arma3-server-console-05-01-2015-22-20-22.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan  5 22:31 arma3-server-console-05-01-2015-22-31-51.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan  5 22:40 arma3-server-console-05-01-2015-22-40-39.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan  5 22:42 arma3-server-console-05-01-2015-22-42-11.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan  5 22:45 arma3-server-console-05-01-2015-22-45-38.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan  6 05:00 arma3-server-console-06-01-2015-05-00-01.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan  6 05:00 arma3-server-console-06-01-2015-20-50-13.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan  6 20:57 arma3-server-console-06-01-2015-20-57-00.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan  6 20:59 arma3-server-console-06-01-2015-20-59-33.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan  6 21:46 arma3-server-console-06-01-2015-21-46-16.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan  7 05:00 arma3-server-console-07-01-2015-05-00-01.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan  7 05:00 arma3-server-console-07-01-2015-07-24-01.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan  7 14:36 arma3-server-console-07-01-2015-14-36-45.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan  7 15:18 arma3-server-console-07-01-2015-15-18-56.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan  7 15:41 arma3-server-console-07-01-2015-15-41-31.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan  7 17:37 arma3-server-console-07-01-2015-17-37-09.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan  7 18:06 arma3-server-console-07-01-2015-18-06-06.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan  7 18:13 arma3-server-console-07-01-2015-18-13-39.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan  7 18:32 arma3-server-console-07-01-2015-18-32-12.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan  7 18:51 arma3-server-console-07-01-2015-18-51-36.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan  7 19:54 arma3-server-console-07-01-2015-19-54-24.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan  7 21:46 arma3-server-console-07-01-2015-21-47-04.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan  7 21:52 arma3-server-console-07-01-2015-21-52-45.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan  7 21:54 arma3-server-console-07-01-2015-21-54-26.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan  8 05:00 arma3-server-console-08-01-2015-05-00-01.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan  8 05:00 arma3-server-console-08-01-2015-14-48-01.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan  8 14:51 arma3-server-console-08-01-2015-14-51-01.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan  8 14:59 arma3-server-console-08-01-2015-14-59-01.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan  8 19:58 arma3-server-console-08-01-2015-19-58-19.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan  8 22:43 arma3-server-console-08-01-2015-22-43-26.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan  8 22:46 arma3-server-console-08-01-2015-22-45-41.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan  9 05:00 arma3-server-console-09-01-2015-05-00-01.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan  9 05:00 arma3-server-console-09-01-2015-19-52-24.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan 10 05:00 arma3-server-console-10-01-2015-05-00-01.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan 10 05:00 arma3-server-console-10-01-2015-20-14-02.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan 10 20:14 arma3-server-console-10-01-2015-20-21-05.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan 10 20:24 arma3-server-console-10-01-2015-20-24-01.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan 10 23:43 arma3-server-console-10-01-2015-23-43-43.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan 11 00:43 arma3-server-console-11-01-2015-00-43-39.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan 11 05:00 arma3-server-console-11-01-2015-05-00-01.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan 11 05:00 arma3-server-console-11-01-2015-14-33-23.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan 11 14:41 arma3-server-console-11-01-2015-14-41-54.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan 11 14:42 arma3-server-console-11-01-2015-14-42-17.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan 11 14:46 arma3-server-console-11-01-2015-14-46-01.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan 11 14:47 arma3-server-console-11-01-2015-14-46-59.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan 11 18:18 arma3-server-console-11-01-2015-18-18-01.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan 12 05:00 arma3-server-console-12-01-2015-05-00-01.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan 12 05:00 arma3-server-console-13-01-2015-05-00-01.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan 13 19:47 arma3-server-console-13-01-2015-19-47-13.log
-rw-rw-r-- 1 arma3server arma3server    0 Jan 13 19:55 arma3-server-console-13-01-2015-19-55-11.log

**Comment by dgibbs64** [comment]
Its because the specific file arma3-server-console.log is missing at the time the server is sending the email. Im not sure why its missing or if that is meant to do that (i havent worked on this function for a while) . Either way this needs looking at. Also your logs are all empty still for some reason.

**Comment by KeanePW** [comment]
It's interesting that they're empty. I guess those console logs are supposed to be filled up with the netlogs we discussed in the other issue we just closed. The netlogs seem to be the data I see when opening the console itself. I'm happy to be contributing! Thank you for your inspiring work.

**Comment by dgibbs64** [comment]
Looks simular to this issue https://github.com/dgibbs64/linuxgameservers/issues/218. Looks like i investigated this before and was unable to replicate. Its almost as if arma3-server-console.log is never being created.

What distro you running?

**Comment by dgibbs64** [comment]
I have an update to this issue tmux 1.8 has a bug that stops console log from working. Closing this issue.
