### ISSUE TITLE
Arma3Server Difficulty Settings

### ISSUE THREAD

**Issue by tranqu91** [dgibbs64/linuxgameservers#278]
I set up the server with the script which worked fine, and the server runs great. I also know how to add mods to the mix, and add server keys, and so far I am happy.
The only thing I can not get to work is the server.Arma3Profile, which stores the difficulty settings. 
We want to allow only 3rd Person perspective off on our server, and this would have to be edited in this profile file.
However it was not created in the installation in the serverfiles where the other files are.
After some googling I found out that linux server like that file under ~/.local/share/Arma 3 -Other Profiles (with escape slashes obviously). There even was a folder called Player, so obviously something happened, but when I edited settings inside Player, it did not change difficulty settings on the server.
I tried a lot, like creating new folders there, adding -name=***.Arma3Profile to the launch options, and can not think of anything else...
someone please help me :)

**Comment by dgibbs64** [comment]
This is not the sort of question I would be able to answer. However any arma 3 server admins may be able to help. Its worth asking on the Arma 3 forums you will probably get a quicker and better answer.

**Comment by AlienXAXS** [comment]
This can be closed @dgibbs64 - he's already getting help from https://github.com/dgibbs64/linuxgameservers/issues/270.
