### ISSUE TITLE
[TS3] Update Command ?

### ISSUE THREAD

**Issue by DSDV** [dgibbs64/linuxgameservers#279]
Hi folks,
i allready have a TS3 server...
but on my root i try to setup a backupserver i case the old one crashes or some friends need one etc.

So cause i love gibbs gsm i also used it for setting up a ts3 BUT how can i update the server?

i used provided link from 4net players (cause im lazy) so now i ned to update the server to newest version - but how?

with best +DS_DV+

**Comment by AlienXAXS** [comment]
Hey, download the latest 64bit build of teamspeak 3 here:
*cd to your teamspeak3 directory
*./ts3server stop
*wget http://dl.4players.de/ts/releases/3.0.11.2/teamspeak3-server_linux-amd64-3.0.11.2.tar.gz
*tar -xvf teamspeak3-server_linux-amd64-3.0.11.2.tar.gz
*rm teamspeak3-server_linux-amd64-3.0.11.2.tar.gz
*cp -r teamspeak3-server_linux-amd64/* ./
*./ts3server start

Should work, take a backup before hand please :)

**Comment by DSDV** [comment]
oh thanks :D

it worked!


btw does anyone know why all the starboudn script threads got closed ?
id love to set up a server for that game!

**Comment by dgibbs64** [comment]
There is no update feature on Teamspeak as they don't provide any good mechanism like steamcmd for updating and I would have to manually update the script every time they update the server which I wont be able to do in a timely manor. But as @AlienXAXS advises that is the best way. I will eventually document this once the new wiki is all sorted. :)

Also see this comment about why your starbound request was canceled https://github.com/dgibbs64/linuxgameservers/issues/268#issuecomment-71102715
