### ISSUE TITLE
[KillingFloor] Unable to start server

### ISSUE THREAD

**Issue by Xylemon** [dgibbs64/linuxgameservers#282]
Since I've updated all the functions and scripts, Killing Floor no longer starts: 

kfserver start
tail: cannot open '3' for reading: No such file or directory
/linktoscript/kf/functions/fn_start: line 47: [: : integer expression expected
[ FAIL ] Starting kf-server: Unable to start Killing Floor Server
	Check log files: /linktoscript/kf/log

The logs just says:

Jan 30 23:11:07 kf-server: Starting: Killing Floor Server
Jan 30 23:11:08 kf-server: Starting: Rotating log files

Distro Details:

Distro:   Slackware 14.1
Arch:   x86_64
Kernel:   3.14.18
tmux:   tmux 1.8
GLIBC:   2.19

I did comment about this in another issue thinking the two might be related, but ended up creating a separate issue since it was more appropriate.

**Comment by dgibbs64** [comment]
Tested this on CentOS and there is no error. Im guessing that Slackware is playing silly buggers again. Here is the offending code. My guess is that tmux -V part of the code is not returning an integer. Even though when I have tested in on other distros it works.


    # tmux pipe-pane not supported in tmux versions < 1.6
    if [ "$(tmux -V|sed "s/tmux //"|sed -n '1 p'|tr -cd [:digit:]|tail -c 3)" -lt "16" ]; then
    	echo "Console logging disabled: Tmux => 1.6 required" >> "${consolelog}"
    	echo "Currently installed: $(tmux -V)" >> "${consolelog}"
    else
    	tmux pipe-pane -o -t ${servicename} "exec cat >> '${consolelog}'"
    fi

**Comment by Xylemon** [comment]
What can I do to help solve this issue? I would like to get my Killing Floor server back up as soon as possible.

**Comment by dgibbs64** [comment]
Not sure I may require access to a slackware vps so I can investigate this. OVH don't do that as an option. I will test again on centos to be sure that this is only a Slackware issue.

**Comment by edgr** [comment]
I am having the same problem with my Ubuntu 14.04 installation.

The log ends with Rotating log files

**Comment by dgibbs64** [comment]
fixed

https://github.com/dgibbs64/linuxgameservers/commit/29d80e88ce8d8b44dbece05cb33c9ab64e9067fd

**Comment by Xylemon** [comment]
Sadly this did not fix the issue.

**Comment by dgibbs64** [comment]
What error are you getting now?

**Comment by Xylemon** [comment]
Just:

[ FAIL ] Starting kf-server: Unable to start Killing Floor Server
Check log files: /linktoscript/kf/log

Log files still empty sadly.

**Comment by dgibbs64** [comment]
Making some progress. Try debug mode. I want to see what that says

**Comment by dgibbs64** [comment]
The brrn investigating the issue and looks like the server is simply failing to start. I think debug mode will reveal the issue.

**Comment by dgibbs64** [comment]
What version of tmux are you using? Just found that version 1.8 has a bug in which pipe-pane does not work.

**Comment by Xylemon** [comment]
OK seems the issue was a silly mistake in the script (I think it was something I did). Basically it was that in the parameters section "ini=" was set to something different. Setting it to "ini=${servercfg}" fixed everything, thanks for suggesting debug mode! I also did update Tmux to the 1.9a just now to avoid any issues with Tmux comparability.

**Comment by dgibbs64** [comment]
Awesome. I will be adding using debug mode in to the error message. To remind Admins to use that feature when having problems. I will also be adding a message in about tmux 1.8 bug.
