### ISSUE TITLE
E-Mail Notification Error

### ISSUE THREAD

**Issue by AlucardXP** [dgibbs64/linuxgameservers#287]
I'm receiving an error when I try to send a a test email to myself. I'm getting this error - 

[csgoserver@gameserver ~]$ ./csgoserver email-test
[ .... ] Email csgo-server: Sending notification to my email/home/csgoserver/functions/fn_details_distro: command substitution: line 55: syntax error near unexpected token `|'
/home/csgoserver/functions/fn_details_distro: command substitution: line 55: `free ${option} | | awk '/Swap:/ {print $2}')'
/home/csgoserver/functions/fn_details_distro: command substitution: line 55: syntax error near unexpected token `|'
/home/csgoserver/functions/fn_details_distro: command substitution: line 55: `free ${option} | | awk '/Swap:/ {print $2}')'

I'm running CentOS 6.6 x64

When I run debug, it shows 

Distro: CentOS release 6.6 (Final)
Arch: x86_64
Kernel: 2.6.32-042stab103.6
Hostname: gameserver

I am guessing its also supposed to display tmux and glibc.

**Comment by dgibbs64** [comment]
Fixed

https://github.com/dgibbs64/linuxgameservers/commit/ac8cfe6286849f685b81f28c40537ca64bfc3b8f
