### ISSUE TITLE
cs go script help

### ISSUE THREAD

**Issue by yossss** [dgibbs64/linuxgameservers#288]
Hello, I found your page and it saved me many hours thousand thanks

I have a dedicated server through a VPS

Yes have tried to change maxplayers the script o little else but it has not worked

can you please tell me how I change the script a little spruce for my own needs

have tested it says on the page but it does not work :( sorry for my english

**Comment by Scarsz** [comment]
Line 31
https://github.com/dgibbs64/linuxgameservers/blob/master/CounterStrikeGlobalOffensive/csgoserver#L31

**Comment by yossss** [comment]
No, what I mean is

I want to change the script and then it does not work

To remove bots and a bit these kinds of things where should I write it and why can not I play if I change the script?

I'm running on Ubuntu

**Comment by dgibbs64** [comment]
http://danielgibbs.co.uk/lgsm/csgoserver/#Server_Details

http://danielgibbs.co.uk/lgsm/csgoserver/#Configuration

**Comment by yossss** [comment]
I am trying to fix a cs server but it does not download anything then it is

* TMUX is required to run this server.
         * Please see 'Prerequisites' section of the installation instructions.

and cs go did not work to change the script done as you said

**Comment by MeltedLux** [comment]
You need to have tmux installed.

**Comment by yossss** [comment]
thanks i try to change the script without success and has also followed the instructions without success, how should I do Ther there any good video or help available would be appreciated?

**Comment by dgibbs64** [comment]
My instructions are designed to be a simple as possible. There are thousands of people who have installed the script with no issues. I recommend trying again but taking your time reading though the instructions to make sure you fully understand what you are doing. The fact that you did not install tmux suggests you did not correctly read the instructions.

If you follow the instructions correctly you should have no issues.

**Comment by dgibbs64** [comment]
Having said that....It would be a good idea at some point to have a video created on how to install the server. This is something that could be done at some point.

**Comment by yossss** [comment]
I understand

perform such services that you make script needs?

Or do you know someone who perform these services?

I can only add to Ubuntu without changing anything?

**Comment by dgibbs64** [comment]
If you are unable to complete this yourself i recommend renting a server from a game server provider. There are hundreds of providers out there

**Comment by yossss** [comment]
I already have a server and cs works fine on it, what I need support with is the actual command script if I can make a completely custom or if the finding someone performing such services to me I find it hard for it to work :(
