### ISSUE TITLE
HalfLife DeathMatch

### ISSUE THREAD

**Issue by uGamers** [dgibbs64/linuxgameservers#316]
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://raw.githubusercontent.com/dgibbs64/linuxgameservers/master/HalfLifeDeathmatchClassic/hldmcserver [following]
--2015-03-17 00:09:44--  https://raw.githubusercontent.com/dgibbs64/linuxgameservers/master/HalfLifeDeathmatchClassic/hldmcserver
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 23.235.40.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|23.235.40.133|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-03-17 00:09:44 ERROR 404: Not Found.

Says the script for Halflife Deathmatch is not found.

**Comment by Xylemon** [comment]
That's because it's moved to: https://github.com/dgibbs64/linuxgameservers/tree/master/HalfLifeDeathmatch

**Comment by uGamers** [comment]
ok thanks but that code is not working aswell.

Half Life: Deathmatch
Linux Game Server Manager
by Daniel Gibbs
http://danielgibbs.co.uk
=================================

Installing SteamCMD
=================================
Steam already installed!

Installing Half Life: Deathmatch Server
=================================
./steamcmd.sh: line 29: /home/halflifedeathmatch/steamcmd/linux32/steamcmd: No such file or directory
./steamcmd.sh: line 29: /home/halflifedeathmatch/steamcmd/linux32/steamcmd: No such file or directory
./steamcmd.sh: line 29: /home/halflifedeathmatch/steamcmd/linux32/steamcmd: No such file or directory
./steamcmd.sh: line 29: /home/halflifedeathmatch/steamcmd/linux32/steamcmd: No such file or directory
./steamcmd.sh: line 29: /home/halflifedeathmatch/steamcmd/linux32/steamcmd: No such file or directory
./steamcmd.sh: line 29: /home/halflifedeathmatch/steamcmd/linux32/steamcmd: No such file or directory

**Comment by uGamers** [comment]
I see the directory aswell as the file and it looks like permissions are right but wont install.

**Comment by uGamers** [comment]
Sorry im stupid forgot the required stuff needed on my new box.
